voice_group p3r_its_going_down_now
    voice_keysplit_all voicegroup_allkeysplit_dppt_drum_1
    voice_keysplit voicegroup193, KeySplitTable6Universal
	voice_keysplit voicegroup194, KeySplitTable6Universal
	voice_keysplit voicegroup195, KeySplitTable7Universal
	voice_keysplit voicegroup196, KeySplitTable8Universal
	voice_keysplit voicegroup197, KeySplitTable9Universal
	voice_keysplit voicegroup198, KeySplitTable10Universal
	voice_keysplit voicegroup199, KeySplitTable7Universal
	voice_keysplit voicegroup200, KeySplitTable11Universal
	voice_keysplit voicegroup201, KeySplitTable12Universal
	voice_keysplit voicegroup202, KeySplitTable11Universal
	voice_keysplit voicegroup203, KeySplitTable13Universal
	voice_keysplit voicegroup204, KeySplitTable14Universal
	voice_keysplit voicegroup205, KeySplitTable15Universal
	voice_directsound 60, 0, DirectSoundWaveData_1000008, 255, 249, 0, 235
	voice_keysplit voicegroup206, KeySplitTable16Universal
	voice_keysplit voicegroup207, KeySplitTable17Universal
	voice_keysplit voicegroup208, KeySplitTable17Universal
	voice_keysplit voicegroup209, KeySplitTable17Universal
	voice_keysplit voicegroup210, KeySplitTable13Universal
	voice_keysplit voicegroup211, KeySplitTable17Universal
	voice_keysplit voicegroup212, KeySplitTable18Universal
	voice_keysplit voicegroup213, KeySplitTable19Universal
	voice_keysplit voicegroup214, KeySplitTable10Universal
	voice_keysplit voicegroup215, KeySplitTable9Universal
	voice_keysplit voicegroup216, KeySplitTable19Universal
	voice_keysplit voicegroup217, KeySplitTable9Universal
	voice_keysplit voicegroup218, KeySplitTable19Universal
	voice_keysplit voicegroup219, KeySplitTable20Universal
	voice_keysplit voicegroup220, KeySplitTable21Universal
	voice_keysplit voicegroup221, KeySplitTable22Universal
	voice_keysplit voicegroup222, KeySplitTable16Universal
	voice_keysplit voicegroup223, KeySplitTable13Universal
	voice_keysplit voicegroup224, KeySplitTable10Universal
	voice_keysplit voicegroup225, KeySplitTable20Universal
	voice_keysplit voicegroup226, KeySplitTable20Universal
	voice_keysplit voicegroup227, KeySplitTable23Universal
	voice_keysplit voicegroup228, KeySplitTable23Universal
	voice_keysplit voicegroup229, KeySplitTable23Universal
	voice_keysplit voicegroup230, KeySplitTable24Universal
	voice_keysplit voicegroup231, KeySplitTable22Universal
	voice_keysplit voicegroup232, KeySplitTable22Universal
	voice_keysplit voicegroup233, KeySplitTable25Universal
	voice_keysplit voicegroup234, KeySplitTable25Universal
	voice_keysplit voicegroup235, KeySplitTable12Universal
	voice_keysplit voicegroup236, KeySplitTable16Universal
	voice_keysplit voicegroup237, KeySplitTable24Universal
	voice_directsound 60, 0, DirectSoundWaveData_10004a8, 255, 0, 255, 235
	voice_keysplit voicegroup238, KeySplitTable12Universal
	voice_keysplit voicegroup239, KeySplitTable12Universal
	voice_keysplit voicegroup240, KeySplitTable18Universal
	voice_keysplit voicegroup241, KeySplitTable18Universal
	voice_keysplit voicegroup242, KeySplitTable16Universal
	voice_keysplit voicegroup243, KeySplitTable24Universal
	voice_keysplit voicegroup244, KeySplitTable11Universal
	voice_directsound 60, 0, DirectSoundWaveData_1001f2c, 255, 253, 0, 235
	voice_keysplit voicegroup_trumpet_keysplit, keysplit_trumpet
	voice_keysplit voicegroup246, KeySplitTable21Universal
	voice_keysplit voicegroup247, KeySplitTable26Universal
	voice_keysplit voicegroup248, KeySplitTable27Universal
	voice_keysplit voicegroup249, KeySplitTable28Universal
	voice_keysplit voicegroup250, KeySplitTable28Universal
	voice_keysplit voicegroup251, KeySplitTable19Universal
	voice_keysplit voicegroup252, KeySplitTable29Universal
	voice_keysplit voicegroup253, KeySplitTable27Universal
	voice_keysplit voicegroup254, KeySplitTable25Universal
	voice_keysplit voicegroup255, KeySplitTable26Universal
	voice_keysplit voicegroup256, KeySplitTable19Universal
	voice_keysplit voicegroup257, KeySplitTable20Universal
	voice_keysplit voicegroup258, KeySplitTable27Universal
	voice_keysplit voicegroup259, KeySplitTable29Universal
	voice_keysplit voicegroup260, KeySplitTable30Universal
	voice_keysplit voicegroup261, KeySplitTable11Universal
	voice_keysplit voicegroup262, KeySplitTable27Universal
	voice_keysplit voicegroup263, KeySplitTable30Universal
	voice_keysplit voicegroup264, KeySplitTable31Universal
	voice_keysplit voicegroup265, KeySplitTable31Universal
	voice_keysplit voicegroup266, KeySplitTable13Universal
	voice_keysplit voicegroup267, KeySplitTable7Universal
	voice_keysplit voicegroup268, KeySplitTable14Universal
	voice_keysplit voicegroup269, KeySplitTable30Universal
	voice_keysplit voicegroup270, KeySplitTable7Universal
	voice_keysplit voicegroup271, KeySplitTable14Universal
	voice_keysplit voicegroup272, KeySplitTable32Universal
	voice_keysplit voicegroup273, KeySplitTable15Universal
	voice_keysplit voicegroup274, KeySplitTable33Universal
	voice_keysplit voicegroup275, KeySplitTable34Universal
	voice_keysplit voicegroup276, KeySplitTable14Universal
	voice_keysplit voicegroup277, KeySplitTable28Universal
	voice_keysplit voicegroup278, KeySplitTable33Universal
	voice_keysplit voicegroup279, KeySplitTable8Universal
	voice_directsound 60, 0, DirectSoundWaveData_1005b5c, 255, 0, 255, 235
	voice_keysplit voicegroup280, KeySplitTable8Universal
	voice_keysplit voicegroup281, KeySplitTable7Universal
	voice_keysplit voicegroup282, KeySplitTable15Universal
	voice_keysplit voicegroup283, KeySplitTable18Universal
	voice_keysplit voicegroup284, KeySplitTable31Universal
	voice_keysplit voicegroup285, KeySplitTable33Universal
	voice_keysplit voicegroup286, KeySplitTable33Universal
	voice_keysplit voicegroup287, KeySplitTable34Universal
	voice_keysplit voicegroup288, KeySplitTable34Universal
	voice_directsound 60, 0, DirectSoundWaveData_1007514, 255, 0, 255, 235
	voice_keysplit voicegroup289, KeySplitTable15Universal
	voice_keysplit voicegroup290, KeySplitTable32Universal
	voice_keysplit voicegroup291, KeySplitTable31Universal
	voice_keysplit voicegroup292, KeySplitTable35Universal
	voice_keysplit voicegroup293, KeySplitTable35Universal
	voice_keysplit voicegroup294, KeySplitTable29Universal
	voice_keysplit voicegroup295, KeySplitTable31Universal
	voice_keysplit voicegroup296, KeySplitTable30Universal
	voice_keysplit voicegroup297, KeySplitTable25Universal
	voice_keysplit voicegroup298, KeySplitTable35Universal
	voice_directsound 60, 0, DirectSoundWaveData_1008da0, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1008e98, 255, 242, 0, 235
	voice_keysplit voicegroup299, KeySplitTable34Universal
	voice_directsound 60, 0, DirectSoundWaveData_10094ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1009b80, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100aeac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100c800, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100cbb8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100ec2c, 255, 0, 255, 235
	voice_keysplit voicegroup300, KeySplitTable32Universal
	voice_directsound 60, 0, DirectSoundWaveData_100f5f8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1012b70, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1013b38, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1014134, 255, 0, 255, 235
	voice_keysplit_all voicegroup301
	voice_keysplit_all voicegroup302


	

