voice_group sunshine_orphanage
    voice_keysplit voicegroup_piano_keysplit, keysplit_piano
    voice_keysplit voicegroup193, KeySplitTable6
	voice_keysplit voicegroup194, KeySplitTable6
	voice_keysplit voicegroup195, KeySplitTable7
	voice_keysplit voicegroup196, KeySplitTable8
	voice_keysplit voicegroup197, KeySplitTable9
	voice_keysplit voicegroup198, KeySplitTable10
	voice_keysplit voicegroup199, KeySplitTable7
	voice_keysplit voicegroup200, KeySplitTable11
	voice_keysplit voicegroup201, KeySplitTable12
	voice_keysplit voicegroup202, KeySplitTable11
	voice_keysplit voicegroup203, KeySplitTable13
	voice_keysplit voicegroup204, KeySplitTable14
	voice_keysplit voicegroup205, KeySplitTable15
	voice_directsound 60, 0, DirectSoundWaveData_1000008, 255, 249, 0, 235
	voice_keysplit voicegroup206, KeySplitTable16
	voice_keysplit voicegroup207, KeySplitTable17
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup209, KeySplitTable17
	voice_keysplit voicegroup210, KeySplitTable13
	voice_keysplit voicegroup211, KeySplitTable17
	voice_keysplit voicegroup212, KeySplitTable18
	voice_keysplit voicegroup208, KeySplitTable17
	voice_keysplit voicegroup214, KeySplitTable10
	voice_keysplit voicegroup215, KeySplitTable9
	voice_keysplit voicegroup216, KeySplitTable19
    voice_keysplit voicegroup217, KeySplitTable9
	