voice_group xc2_garfont_mercernaries
    voice_keysplit voicegroup_piano_keysplit, keysplit_piano
    voice_keysplit voicegroup193, KeySplitTable6Universal
	voice_keysplit voicegroup194, KeySplitTable6Universal
	voice_keysplit voicegroup195, KeySplitTable7Universal
	voice_keysplit voicegroup196, KeySplitTable8Universal
	voice_keysplit voicegroup197, KeySplitTable9Universal
	voice_keysplit voicegroup198, KeySplitTable10Universal
	voice_keysplit voicegroup199, KeySplitTable7Universal
	voice_keysplit voicegroup200, KeySplitTable11Universal
	voice_keysplit voicegroup201, KeySplitTable12Universal
	voice_keysplit voicegroup202, KeySplitTable11Universal
	voice_keysplit voicegroup203, KeySplitTable13Universal
	voice_keysplit voicegroup204, KeySplitTable14Universal
	voice_keysplit voicegroup205, KeySplitTable15Universal
	voice_directsound 60, 0, DirectSoundWaveData_1000008, 255, 249, 0, 235
	voice_keysplit voicegroup206, KeySplitTable16Universal
	voice_keysplit voicegroup207, KeySplitTable17Universal
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup209, KeySplitTable17Universal
	voice_keysplit voicegroup210, KeySplitTable13Universal
	voice_keysplit voicegroup211, KeySplitTable17Universal
	voice_keysplit voicegroup212, KeySplitTable18Universal
	voice_keysplit voicegroup208, KeySplitTable17Universal
	voice_keysplit voicegroup214, KeySplitTable10Universal
	voice_keysplit voicegroup215, KeySplitTable9Universal
	voice_keysplit voicegroup216, KeySplitTable19Universal
    voice_keysplit voicegroup217, KeySplitTable9Universal

