#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_M,
    MUGSHOT_A,
    MUGSHOT_S,
    MUGSHOT_INTELEON,
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_NORMAL = 0,
    EMOTE_HAPPY,
    EMOTE_SAD,
    EMOTE_MAD,
    EMOTE_SURPRISED,
    EMOTE_TIRED,
    EMOTE_DOUBT,
    EMOTE_DARKENED,
    EMOTE_SMILE,
    EMOTE_STRUGGLED,
    EMOTE_SILHOUETTE,
    EMOTE_SERIOUS,
    EMOTE_CONFIDENT,
    EMOTE_GEEZ,
    EMOTE_CRY,
    EMOTE_PENSIVE,
    EMOTE_COUNT,
};

#define MUGSHOT_M 1 //total: 11
#define MUGSHOT_A 2 //total: 13
#define MUGSHOT_S 3 //total: 9
#define MUGSHOT_INTELEON 4 //total: 3
#define MUGSHOT_COUNT 36

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H