#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/heal_locations.json and Inja template src/data/heal_locations.constants.json.txt
//


enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_SUNSHINE_TOWN,
    HEAL_LOCATION_ROUTE2_HOUSE,
    HEAL_LOCATION_CORALPORT,
    HEAL_LOCATION_MANSIONS_GARDEN,
    HEAL_LOCATION_ROUTE2_2,
    HEAL_LOCATION_SUNSHINE_ORPHANAGE,
    HEAL_LOCATION_WINDWARD_PORT,
    NUM_HEAL_LOCATIONS
};

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
