// Add new IDs here
enum {
    HELP_POKEDEX,
    HELP_SHINY_CHANCE,
    HELP_STORY_STARTER,
    HELP_COMPANION_MENU,
    HELP_QUEST_MENU,
    HELP_MAKE_CHOICES,
    HELP_DEADLINE,
    HELP_PART_TIME,
    HELP_GIMMIGHOUL_COINS,
    HELP_MEGA_EVOLUTION,
    HELP_COUNT
};
