// Add new IDs here
enum {
    HELP_POKEDEX,
    HELP_SHINY_CHANCE,
    HELP_STORY_STARTER,
    HELP_SPEED_UP,
    HELP_COMPANION_MENU,
    HELP_QUEST_MENU,
    HELP_MAKE_CHOICES,
    HELP_DEADLINE,
    HELP_DUNGEON_ENCOUNTER,
    HELP_EXIT_DUNGEON,
    HELP_PROTAGONISTS,
    HELP_PART_TIME,
    HELP_DEXNAV,
    HELP_BOX_LINK,
    HELP_GIMMIGHOUL_COINS,
    HELP_MEGA_EVOLUTION,
    HELP_COUNT
};
