#ifndef GUARD_CONSTANTS_MAP_EVENT_IDS_H
#define GUARD_CONSTANTS_MAP_EVENT_IDS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/*/map.json
//

// MAP_CORALPORT
#define A_CORAL 23
#define M_CORAL 24
#define S_CORAL 25
#define MIKU_CORAL 33
#define EMI_CORAL 34

// MAP_CORALPORT_POLICE_STATION
#define A_CORALP 8
#define M_CORALP 9
#define S_CORALP 10

// MAP_KIRIJOS_MANSION_MAIN_HALL
#define LOCALID_TAKEHARU 1
#define LOCALID_INTELEON 2
#define LOCALID_BUTLER 3

// MAP_MANSION_TRAINING_HOUSE
#define LOCALID_MANSION_TRAINING_HOUSE_NURSE 1

// MAP_MITSURUS_ROOM2F
#define LOCALID_VULPIX 2

// MAP_MANSIONS_GARDEN
#define KIKUNO 22
#define FENNEKIN 23
#define INDEEDEE_F 24
#define FURFROU 26

// MAP_ROUTE2
#define SHINJIRO 6
#define TAROU 14
#define KYOUSUKE 17

// MAP_ROUTE2_GATEHOUSE
#define LOCALID_ROUTE2_GATEHOUSE_NURSE 2

// MAP_SUNSHINE_ORPHANAGE_MAIN_HALL
#define LOCALID_SUNSHINE_ORPHANAGE_BLISSEY 11

// MAP_SUNSHINE_TOWN_RIVERBANK
#define SQUIRTLE_Q 5

// MAP_SUNSHINE_TOWN_POKEMON_CENTER
#define LOCALID_SUNSHINETOWN_NURSE 2

// MAP_SUNSHINE_WOODS
#define INTELEON_T_SW 13

// MAP_THUNDERSTONE_SCREE_1F
#define NB_TDS 1
#define NB_R 5

// MAP_WINDWARD_PORT
#define CHAKAMARU_WWP 21
#define ICHI_WWP 22

// MAP_WINDWARD_PORT_HARBOR
#define A_WP 13
#define M_WP 14
#define S_WP 15
#define GHOSTBOY 16

// MAP_WINDWARDPORT_MAYOIDOS_LAB
#define MAYOIDO_WWH 1
#define WACHI_WWH 2
#define IRIA_WWH 3
#define SINISTCHA_WWH 4
#define AEGISLASH_WWH 5
#define A_WWH 6
#define S_WWH 7
#define M_WWH 8
#define OSHA_WWH 9
#define GROO_WWH 10

#endif // GUARD_CONSTANTS_MAP_EVENT_IDS_H
