#ifndef GUARD_CONSTANTS_OUTFITS_H
#define GUARD_CONSTANTS_OUTFITS_H

//! macro modes

// ScrCmd_getoutfitstatus
#define OUTFIT_CHECK_FLAG 0
#define OUTFIT_CHECK_USED 1

// ScrCmd_toggleoutfit
#define OUTFIT_TOGGLE_UNLOCK 0
#define OUTFIT_TOGGLE_LOCK 1

// BufferOutfitStrings
#define OUTFIT_BUFFER_NAME  0
#define OUTFIT_BUFFER_DESC  1

//! outfits
#define CHARACTER_NONE 0
#define CHARACTER_MITSURU 1
#define CHARACTER_AKIHIKO 2
#define CHARACTER_SHINJIRO 3
#define CHARACTER_INTELEON_T 4
#define CHARACTER_COUNT 5

// inclusive
#define CHARACTER_BEGIN CHARACTER_MITSURU
#define CHARACTER_END   CHARACTER_INTELEON_T

#define DEFAULT_CHARACTER CHARACTER_MITSURU

#endif //! GUARD_CONSTANTS_OUTFITS_H
