#ifndef GUARD_REMATCHES_H
#define GUARD_REMATCHES_H

enum {
    REMATCH_TABLE_ENTRIES // The total number of rematch entries. Must be last in enum
};

#define REMATCH_SPECIAL_TRAINER_START   REMATCH_TABLE_ENTRIES
#define REMATCH_ELITE_FOUR_ENTRIES      REMATCH_TABLE_ENTRIES

#endif // GUARD_REMATCHES_H
