#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_A,
    SP_NAME_M,
    SP_NAME_S,
    SP_NAME_MK,
    SP_NAME_KBYS,
    SP_NAME_KRSW,
    SP_NAME_ITLN,
    SP_NAME_TKHR,
    SP_NAME_KKN,
    SP_NAME_MIB,
    SP_NAME_WIB,
    SP_NAME_KGS,
    SP_NAME_PROF,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
