#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_AKIHIKO,
    SP_NAME_MITSURU,
    SP_NAME_SHINJIRO,
    SP_NAME_MIKI,
    SP_NAME_KOBAYASHI,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
