#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     10
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     3
#define HIDDEN_WILD_COUNT   1
#define FISH_WILD_COUNT     8

#define DN_FISH_WILD_COUNT          3//only 3 icons shown in DN fish section
#define OLDROD_WILD_COUNT           2
#define GOODROD_WILD_COUNT          3
#define SUPERROD_WILD_COUNT         3
#define GOODROD_WILD_COUNT_START    OLDROD_WILD_COUNT
#define GOODROD_WILD_COUNT_END      (GOODROD_WILD_COUNT_START + DN_FISH_WILD_COUNT)
#define SUPERROD_WILD_COUNT_START   GOODROD_WILD_COUNT_END
#define SUPERROD_WILD_COUNT_END     (SUPERROD_WILD_COUNT_START + DN_FISH_WILD_COUNT)
#define DN_ICON_COUNT               (WATER_WILD_COUNT + LAND_WILD_COUNT + HIDDEN_WILD_COUNT + FISH_WILD_COUNT)


#define NUM_ALTERING_CAVE_TABLES 9

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
