Windwardport_House_2_2F_MapScripts::
	.byte 0


Windwardport_House_2_2F_Girl::
# 4 "data/maps/Windwardport_House_2_2F/scripts.pory"
	lock
# 5 "data/maps/Windwardport_House_2_2F/scripts.pory"
	faceplayer
# 6 "data/maps/Windwardport_House_2_2F/scripts.pory"
	setspeaker Windwardport_House_2_2F_Girl_Text_0
# 7 "data/maps/Windwardport_House_2_2F/scripts.pory"
	msgbox Windwardport_House_2_2F_Girl_Text_1
# 9 "data/maps/Windwardport_House_2_2F/scripts.pory"
	release
	end


Windwardport_House_2_2F_Girl_Text_0:
# 6 "data/maps/Windwardport_House_2_2F/scripts.pory"
	.string "Okayo$"

Windwardport_House_2_2F_Girl_Text_1:
# 7 "data/maps/Windwardport_House_2_2F/scripts.pory"
	.string "I'm studying hard for Kyoui College's\n"
	.string "entrance exam.\p"
	.string "It's happening in 2 months.\n"
	.string "I'm so nervous.$"
