gText_Birch_Welcome::
	.string "This game is a project of passion\n"
	.string "and is completely free.\p"
	.string "If you paid for this game\n"
	.string "you have been scammed.\p"
	.string "The prologue quest, starter Pokémon\n"
	.string "and starting location is different\n"
	.string "based on your character's gender.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "If you paid for this game\n"
	.string "you have been scammed.\p"
	.string "The prologue quest, starter Pokémon\n"
	.string "and starting location is different\n"
	.string "based on your character's gender.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "This game is a project of passion and\n"
	.string "is completely free.\p"
	.string "If you paid for this game, you have\n"
	.string "been scammed.\p"
	.string "The prologue quest, starter Pokémon and\n"
	.string "starting location is different based on\l"
	.string "your chosen main character.\p"
	.string "You can choose to experience the other's\n"
	.string "prologue quest later as you proceed.\n"
	.string "(If I can code it :P)\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "So which character do you want\n"
	.string "to play as?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Akihiko or Mitsuru?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "So it's {PLAYER}?\p"
	.string "$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer::
	.string "Great! If you have any question,\n"
	.string "feel free to contact me on SNS.\p"
	.string "$"


gText_Birch_AreYouReady::
	.string "Documents for this game can be found at\n"
	.string "(place holder).\l"
	.string "Please enjoy :D.\p"
	.string "$"
