gText_NewGame_Intro::
	.string "This game is a project of passion and is\n"
	.string "completely free.\p"
	.string "If you paid for this game, you have been\n"
	.string "scammed.\p"
	.string "The prologue quest, starter Pokémon\n"
	.string "and starting location is different\l"
	.string "based on your chosen main character.\p"
	.string "You can choose to experience the\n"
	.string "other's prologue quest later as you\l"
	.string "proceed.{PAUSE_UNTIL_PRESS}$"

gText_NewGame_WhichCharacter::
	.string "So which character do you want to play\n"
	.string "as?{PAUSE_UNTIL_PRESS}$"

gText_NewGame_AkiOrMitsu::
	.string "Akihiko or Mitsuru?$"

gText_NewGame_SoItsPlayer::
	.string "So it's {PLAYER}?$"

gText_NewGame_WhatDifficulty::
	.string "What difficulty would you like to play\n"
	.string "with?$"

gText_NewGame_ChoosingCasual::
	.string "Confirm choosing {COLOR RED}Casual {COLOR 2}mode?\n"
	.string "{COLOR 7}You will not be able to choose a higher\l"
	.string "difficulty later.$"

gText_NewGame_ChoosingStory::
	.string "Confirm choosing {COLOR RED}Story {COLOR 2}mode?\n"
	.string "{COLOR 7}You will be able to choose a different\l"
	.string "difficulty later, {COLOR RED}except for Merciless\l"
	.string "mode.$"

gText_NewGame_ChoosingMerciless::
	.string "Confirm choosing {COLOR RED}Merciless {COLOR 2}mode?\n"
	.string "{COLOR 7}You will be able to choose a lower\l"
	.string "difficulty later.$"

gText_NewGame_DifficultyInfos::
	.string "In {COLOR 7}Casual Mode{COLOR 2}, you can expect the\n"
	.string "game's difficulty to be on par with\l"
	.string "official games'.\p"
	.string "A story starter can be put into any\n"
	.string "protagonist's team.\p"
	.string "Recommended for new and/or players\n"
	.string "that just want to enjoy the story.\p"
	.string "In {COLOR 7}Story Mode{COLOR 2}, the battle will be a bit\n"
	.string "more challenging than those in official\l"
	.string "games, with key battles having proper\l"
	.string "strategy.\p"
	.string "A story starter can only be put into its\n"
	.string "respective protagonist's team to stay\l"
	.string "true to the story.\p"
	.string "Recommended for players with\n"
	.string "experience in battle.\p"
	.string "In {COLOR 7}Merciless Mode{COLOR 2}, your team will always\n"
	.string "be at a lower level than the opponents'.\p"
	.string "Your protagonist's story starter\n"
	.string "cannot be deposited nor released.\p"
	.string "The money reward will also be reduced.\p"
	.string "Not recommended for your first time\n"
	.string "playing this game.$"

gText_NewGame_Outro::
	.string "Great! If you have any question, feel\n"
	.string "free to contact me on SNS.\p"
	.string "Documents for this game can be found\n"
	.string "at (place holder).\p"
	.string "Please enjoy :D.$"
