gText_Birch_Welcome::
	.string "This game is a project of passion\n"
	.string "and is completely free.\p"
	.string "If you paid for this game\n"
	.string "you have been scammed.\p"
	.string "The prologue quest, starter Pokemon\n"
	.string "and starting location is different\n"
	.string "based on your character's gender.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "If you paid for this game\n"
	.string "you have been scammed.\p"
	.string "The prologue quest, starter Pokemon\n"
	.string "and starting location is different\n"
	.string "based on your character's gender.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "If you paid for this game\n"
	.string "you have been scammed.\p"
	.string "The prologue quest, starter Pokemon\n"
	.string "and starting location is different\l"
	.string "based on your character's gender.\p"
	.string "You can still choose to experience\n"
	.string "the other character's quest later\l"
	.string "in the story.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "So which character do you want\n"
	.string "to play as?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Akihiko or Mitsuru?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "So it's {PLAYER}{KUN}?\p"
	.string "$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Great! If you have any question,\n"
	.string "feel free to contact me on SNS.\p"
	.string "$"


gText_Birch_AreYouReady::
	.string "Documents for this game can\l"
	.string "be found at (place holder).\n"
	.string "Please enjoy :D.\p"
	.string "$"
