gText_ObtainedTheItem::
	.string "Obtained the {COLOR 7}{STR_VAR_2}{COLOR 2}!$"

gText_TheBagIsFull::
	.string "The {COLOR 11}Bag{COLOR 2} is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {COLOR 7}{STR_VAR_2}{COLOR 2}\n"
	.string "in the {COLOR 11}{STR_VAR_3}{COLOR 2} Pocket.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {COLOR 7}{STR_VAR_2}{COLOR 2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The {COLOR 11}Bag {COLOR 2}is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {COLOR 11}Bag{COLOR 2}.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Obtained {COLOR 7}{STR_VAR_1} {STR_VAR_2}{COLOR 2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} found {COLOR 7}{STR_VAR_1} {STR_VAR_2}{COLOR 2}!$"
