Windwardport_Juis_House_2F_MapScripts::
	.byte 0


Windwardport_Juis_House_ChimcharDoll::
# 4 "data/maps/Windwardport_Juis_House_2F/scripts.pory"
	lock
# 5 "data/maps/Windwardport_Juis_House_2F/scripts.pory"
	msgbox Windwardport_Juis_House_ChimcharDoll_Text_0
# 6 "data/maps/Windwardport_Juis_House_2F/scripts.pory"
	mcsaid EMOTE_SMILE
# 7 "data/maps/Windwardport_Juis_House_2F/scripts.pory"
	msgbox Windwardport_Juis_House_ChimcharDoll_Text_1
# 8 "data/maps/Windwardport_Juis_House_2F/scripts.pory"
	release
	end


Windwardport_Juis_House_ChimcharDoll_Text_0:
# 5 "data/maps/Windwardport_Juis_House_2F/scripts.pory"
	.string "It's a Chimchar doll.$"

Windwardport_Juis_House_ChimcharDoll_Text_1:
# 7 "data/maps/Windwardport_Juis_House_2F/scripts.pory"
	.string "(Looks like it holds a lot of memories.)$"
