.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "Oh? Did you want to make some {POKEBLOCK}s\n"
	.string "with this old-timer?$"

BerryBlender_Text_Excellent:
	.string "Excellent!$"

BerryBlender_Text_MadeOldTimerSad:
	.string "Oh…\n"
	.string "You've made this old-timer sad…$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "Do you know how to make a {POKEBLOCK}?$"

BerryBlender_Text_LetsBerryBlender:
	.string "Let's get started, then!\p"
	.string "Let's Berry Blender!$"

BerryBlender_Text_ExplainBerryBlending:
	.string "Okay, a little explanation, then.\p"
	.string "Oh, don't worry, it's quite simple.\p"
	.string "When the Blender's arrow comes to\n"
	.string "your marker, just press the A Button.\p"
	.string "That's all you have to do.\n"
	.string "You'll see how easy it is when you try.$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "Oh?\n"
	.string "You don't have any Berries?\p"
	.string "If you don't have any Berries,\n"
	.string "you can't make any {POKEBLOCK}s.$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "Well, that won't do at all now, will it?\p"
	.string "If you don't mind leftovers, you can\n"
	.string "have one of my Berries.\p"
	.string "That way, we could make some {POKEBLOCK}s\n"
	.string "together using the Berry Blender.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "If I had some Berries left over,\n"
	.string "I'd gladly give you one…\p"
	.string "But, I don't have any to spare today.\n"
	.string "We'll have to do this another time.$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "But your {POKEBLOCK} Case is full.\p"
	.string "You should use some {POKEBLOCK}s before\n"
	.string "you come see me again.$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "But you don't have a {POKEBLOCK} Case.\p"
	.string "You should get a {POKEBLOCK} Case and then\n"
	.string "come see me.$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "Let's get blending already!$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "I wonder what kind of {POKEBLOCK} I'll get?\n"
	.string "This is so exciting!$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "Hi, there! Did you want to blend some\n"
	.string "{POKEBLOCK}s with us?$"

BerryBlender_Text_Okay:
	.string "Okay!$"

BerryBlender_Text_ThatsTooBad:
	.string "That's too bad…\p"
	.string "But we'll always be around whenever\n"
	.string "you get the urge to blend!$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "Of course, you do know how to\n"
	.string "blend {POKEBLOCK}s, don't you?$"

BerryBlender_Text_LetsBerryBlender2:
	.string "Let's get started, then!\p"
	.string "Let's Berry Blender!$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "Okay!\n"
	.string "Let me explain it to you!\p"
	.string "When the spinning Blender's arrow\n"
	.string "reaches your marker, just press\l"
	.string "the A Button.\p"
	.string "That's all it takes.\n"
	.string "Pretty easy, don't you think?$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "Oh, but wait a second here…\n"
	.string "You don't have any Berries.\p"
	.string "You can't make any {POKEBLOCK}s without\n"
	.string "Berries…\p"
	.string "We'll always be around whenever you\n"
	.string "get hold of some Berries to blend.$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "Oh, but wait a second here…\n"
	.string "Your {POKEBLOCK} Case is full.\p"
	.string "You should use some {POKEBLOCK}s and\n"
	.string "then come back.$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "Oh, but wait a second here…\n"
	.string "You don't have a {POKEBLOCK} Case.\p"
	.string "You should get a {POKEBLOCK} Case and\n"
	.string "then come back.$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "Oh, hello! Did you want to make some\n"
	.string "{POKEBLOCK}s with our little group?$"

BerryBlender_Text_OhDear:
	.string "Oh, dear!$"

BerryBlender_Text_LeftUsInShock:
	.string "Oh, dear me…\p"
	.string "You've left us in shock!$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "Naturally, you know how to make\n"
	.string "{POKEBLOCK}s, don't you?$"

BerryBlender_Text_LetsBerryBlender3:
	.string "Okay, dear!\n"
	.string "Let's get started!\p"
	.string "Let's Berry Blender!$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "Oh, dear!\p"
	.string "Then, I'll explain it to you nicely.\p"
	.string "When the Blender's arrow spins to\n"
	.string "your marker, press the A Button.\p"
	.string "That's all it takes.\n"
	.string "Isn't it simple?$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "You don't have any Berries,\n"
	.string "do you?\p"
	.string "If you don't have any Berries,\n"
	.string "you can't make any {POKEBLOCK}s.\p"
	.string "We'll always be making {POKEBLOCK}s here,\n"
	.string "so let's make some together when\l"
	.string "you get a Berry or two.$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "Your {POKEBLOCK} Case is full,\n"
	.string "it looks like.\p"
	.string "You should use some {POKEBLOCK}s up\n"
	.string "and then come back.$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "You haven't gotten a {POKEBLOCK} Case\n"
	.string "yet, it looks like.\p"
	.string "You need to get a {POKEBLOCK} Case before\n"
	.string "you come back.$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "Okay! Today's going to be the day that\n"
	.string "I set a new Blender speed record!$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "Oh, dear!\n"
	.string "You look as if you're good at blending.\l"
	.string "Would you like to join us?$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "I'm going to make delicious {POKEBLOCK}s\n"
	.string "and make my Pokémon cuter.$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "{POKEBLOCK}s will be made with your friends \n"
	.string "from Berries in the Berry Blender.\p"
	.string "Is it okay to save the game before\n"
	.string "linking with your friends?$"

BerryBlender_Text_SearchingForFriends:
	.string "Searching for your friends…\n"
	.string "… … B Button: Cancel$"

BerryBlender_Text_Player1Arrived:
	.string "{STR_VAR_1} arrived.$"

BerryBlender_Text_Player1And2Arrived:
	.string "{STR_VAR_1} and {STR_VAR_2} arrived.$"

BerryBlender_Text_AllPlayersArrived:
	.string "{STR_VAR_1}, {STR_VAR_2}, and\n"
	.string "{STR_VAR_3} arrived.$"

BerryBlender_Text_NoBerriesLink:
	.string "You have no Berries.\n"
	.string "The Berry Blender can't be used.$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "Your {POKEBLOCK} Case is full.\n"
	.string "The Berry Blender can't be used.$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "You don't have a {POKEBLOCK} Case.\n"
	.string "The Berry Blender can't be used.$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "I love making {POKEBLOCK}s.\p"
	.string "I always have some Berries with me.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "If you'd like, we could make some\n"
	.string "{POKEBLOCK}s together using the\l"
	.string "Berry Blender.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string "Oh?\n"
	.string "You don't have any Berries?\p"
	.string "Well, that won't do at all now, will it?\p"
	.string "If you don't mind leftovers, you can\n"
	.string "have one of my Berries.$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "We'll use it to make {POKEBLOCK}s together\n"
	.string "using the Berry Blender.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string "Oh?\n"
	.string "You don't have any Berries?\p"
	.string "If I had some left over, I'd gladly\n"
	.string "give you one…\p"
	.string "But, I don't have any to spare today.\n"
	.string "Sorry about that.$"
