LilycoveCity_PokemonCenter_1F_EventScript_LilycoveLady::
	
	end

LilycoveCity_PokemonCenter_1F_EventScript_FavorLady::
	
	end

LilycoveCity_PokemonCenter_1F_EventScript_FavorLadyCompleted::
	
	end

LilycoveCity_PokemonCenter_1F_EventScript_FavorLadyReady::
	
	end

LilycoveCity_PokemonCenter_1F_EventScript_TellAboutPlayersItem::
	
	end

LilycoveCity_PokemonCenter_1F_EventScript_PlayerGaveBadThing::
	
	end

LilycoveCity_PokemonCenter_1F_EventScript_PlayerGaveGreatThing::

	end

LilycoveCity_PokemonCenter_1F_EventScript_RequestItem::
	end

LilycoveCity_PokemonCenter_1F_EventScript_DeclineLa::
	end

LilycoveCity_PokemonCenter_1F_EventScript_AcceptLa::
	end

LilycoveCity_PokemonCenter_1F_EventScript_ChooseFavorItem::
	end

LilycoveCity_PokemonCenter_1F_EventScript_AskQuitChooseFavorItem::
	end

LilycoveCity_PokemonCenter_1F_EventScript_GiveFavorItem::
	end

LilycoveCity_PokemonCenter_1F_EventScript_DidntLikeFavorItem::
	end

LilycoveCity_PokemonCenter_1F_EventScript_CheckLovedItem::
	end

LilycoveCity_PokemonCenter_1F_EventScript_LikedFavorItem::
	end

LilycoveCity_PokemonCenter_1F_EventScript_LovedFavorItem::
	end

LilycoveCity_PokemonCenter_1F_EventScript_FavorLadyPrize::
	end

LilycoveCity_PokemonCenter_1F_EventScript_NoRoomForFavorPrize::
	end

LilycoveCity_PokemonCenter_1F_EventScript_ReceivedFavorPrize::
	end

LilycoveCity_PokemonCenter_1F_EventScript_QuizLady::
	end

LilycoveCity_PokemonCenter_1F_EventScript_HasQuiz::

	end

LilycoveCity_PokemonCenter_1F_EventScript_CheckMadeQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_WaitingToTakeYourQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_PlayerQuizReady::
	end

LilycoveCity_PokemonCenter_1F_EventScript_LadyQuizReady::
	end

LilycoveCity_PokemonCenter_1F_EventScript_AskTakeQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_DeclineQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_TakeQuiz::
	

LilycoveCity_PokemonCenter_1F_EventScript_CheckQuizTakingState::
	end

LilycoveCity_PokemonCenter_1F_EventScript_ShowQuestion::

	end

LilycoveCity_PokemonCenter_1F_EventScript_GetAnswer::

	end

LilycoveCity_PokemonCenter_1F_EventScript_AskQuitQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_QuitTakingQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_SubmitQuizResponse::
	end

LilycoveCity_PokemonCenter_1F_EventScript_CorrectResponse::
	end

LilycoveCity_PokemonCenter_1F_EventScript_IncorrectResponse::
	end

@ VAR_RESULT is essentially ignored, both jumps are identical
LilycoveCity_PokemonCenter_1F_EventScript_ReadyGivePrize::
	end

LilycoveCity_PokemonCenter_1F_EventScript_GivePrize1::
	end

LilycoveCity_PokemonCenter_1F_EventScript_GivePrize0::
	end

LilycoveCity_PokemonCenter_1F_EventScript_GivePrize::
	end

LilycoveCity_PokemonCenter_1F_EventScript_NoSpaceForQuizPrize::
	end

LilycoveCity_PokemonCenter_1F_EventScript_AskMakeQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_DeclineMakeQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_MakeQuiz::

LilycoveCity_PokemonCenter_1F_EventScript_PickPrize::
	end

LilycoveCity_PokemonCenter_1F_EventScript_AskQuitChoosingPrize::
	end

LilycoveCity_PokemonCenter_1F_EventScript_WriteQuiz::
	
LilycoveCity_PokemonCenter_1F_EventScript_WriteQuizQuestion::
	end

LilycoveCity_PokemonCenter_1F_EventScript_AskQuitWritingQuizQuestion::
	end

LilycoveCity_PokemonCenter_1F_EventScript_FinishMakingQuiz::
	end

LilycoveCity_PokemonCenter_1F_EventScript_ContestLady::
	end

@ Redundant with above script, VAR_RESULT will always be FALSE here
LilycoveCity_PokemonCenter_1F_EventScript_NotGivenPokeblock::
	end

LilycoveCity_PokemonCenter_1F_EventScript_GivenPokeblock::
	release
	end

LilycoveCity_PokemonCenter_1F_EventScript_AskForPokeblock::
	end

LilycoveCity_PokemonCenter_1F_EventScript_DeclineGivePokeblock::
	end

LilycoveCity_PokemonCenter_1F_EventScript_ChoosePokeblock::
	end

LilycoveCity_PokemonCenter_1F_EventScript_AskQuitGivingPokeblock::
	end

LilycoveCity_PokemonCenter_1F_EventScript_GivePokeblock::
	end

@ VAR_0x8004 here is the return value from GivePokeblockToContestLady
LilycoveCity_PokemonCenter_1F_EventScript_FeedPokeblock::
		end

@ VAR_0x8004 here is the return value from GivePokeblockToContestLady
LilycoveCity_PokemonCenter_1F_EventScript_MonEnjoyPokeblock::
	
LilycoveCity_PokemonCenter_1F_EventScript_FinishFeedPokeblock::
	end

LilycoveCity_PokemonCenter_1F_EventScript_MonDislikedPokeblock::
	end

LilycoveCity_PokemonCenter_1F_EventScript_MonLikedPokeblock::
	end

LilycoveCity_PokemonCenter_1F_EventScript_CheckAirContestLadyShow::
	end

LilycoveCity_PokemonCenter_1F_EventScript_AirContestLadyShow::

	release
	end

LilycoveCity_PokemonCenter_1F_EventScript_NoPokeblockCase::
	release
	end

LilycoveCity_PokemonCenter_1F_Movement_LadyFaceMon:
	face_right
	delay_8
	step_end

LilycoveCity_PokemonCenter_1F_Movement_MonFaceLady:
	face_left
	delay_8
	step_end

@ Unused
LilycoveCity_PokemonCenter_1F_Movement_MonFaceDown:
	face_down
	step_end

LilycoveCity_PokemonCenter_1F_Movement_LadyFacePlayer:
	face_player
	step_end

LilycoveCity_PokemonCenter_1F_Movement_MonJump:
	disable_jump_landing_ground_effect
	jump_in_place_left
	disable_jump_landing_ground_effect
	jump_in_place_left
	step_end

LilycoveCity_PokemonCenter_1F_EventScript_ContestLadyMon::
	end

LilycoveCity_PokemonCenter_1F_EventScript_Zigzagoon::
	end

LilycoveCity_PokemonCenter_1F_EventScript_Skitty::
	end

LilycoveCity_PokemonCenter_1F_EventScript_Poochyena::
	end

LilycoveCity_PokemonCenter_1F_EventScript_Kecleon::
	end

LilycoveCity_PokemonCenter_1F_EventScript_Pikachu::
	end

LilycoveCity_PokemonCenter_1F_Text_ImTheFavorLady:
	.string "I'm the Favor Lady…$"

LilycoveCity_PokemonCenter_1F_Text_ObsessedWithThing:
	.string "I've recently developed an obsession\n"
	.string "for {STR_VAR_1} things…$"

LilycoveCity_PokemonCenter_1F_Text_ThankYouForLastTime:
	.string "Oh…\n"
	.string "Thank you for last time…$"

LilycoveCity_PokemonCenter_1F_Text_PlayerGaveMeBadThing:
	.string "Before, I think it was {STR_VAR_3}…\p"
	.string "{STR_VAR_3} gave me one {STR_VAR_2},\n"
	.string "saying it was {STR_VAR_1}.\p"
	.string "But it wasn't {STR_VAR_1}.\n"
	.string "Not in the least bit.$"

LilycoveCity_PokemonCenter_1F_Text_PlayerGaveMeGreatThing:
	.string "Before, {STR_VAR_3} gave me a very\n"
	.string "{STR_VAR_1} {STR_VAR_2}.\p"
	.string "I cherish it now.$"

LilycoveCity_PokemonCenter_1F_Text_WillYouShareThing:
	.string "Listen, if you have anything that\n"
	.string "is {STR_VAR_1}, will you share it\l"
	.string "with me?$"

LilycoveCity_PokemonCenter_1F_Text_WhatWillYouGiveMe:
	.string "…Really?\n"
	.string "What will you give me?$"

LilycoveCity_PokemonCenter_1F_Text_IsThatSoGoodbye:
	.string "Is that so?\n"
	.string "Then, it's good-bye…$"

LilycoveCity_PokemonCenter_1F_Text_NotWillingToShare:
	.string "Oh…\n"
	.string "You're not willing to share?$"

LilycoveCity_PokemonCenter_1F_Text_IllTryToCherishIt:
	.string "Oh?\n"
	.string "That {STR_VAR_2} is {STR_VAR_1}?\p"
	.string "…Oh, is that right?\p"
	.string "Well, I owe you a thanks anyway.\n"
	.string "I'll try to cherish it…$"

LilycoveCity_PokemonCenter_1F_Text_IWillCherishThis:
	.string "Oh…\p"
	.string "That's a quite {STR_VAR_1}\n"
	.string "{STR_VAR_2}…\p"
	.string "Isn't it nice?\n"
	.string "It's so dreamy…\p"
	.string "Thank you…\n"
	.string "I will cherish this…$"

LilycoveCity_PokemonCenter_1F_Text_IWillTreasureThis:
	.string "…Oh, oh, oh…\p"
	.string "This is amazing!\n"
	.string "This really is {STR_VAR_1}!\p"
	.string "I never knew that one {STR_VAR_2}\n"
	.string "could be this {STR_VAR_1}!\p"
	.string "Thank you!\p"
	.string "I will treasure this for the rest\n"
	.string "of my life!$"

LilycoveCity_PokemonCenter_1F_Text_IllGiveYouThisInReturn:
	.string "I'll give you this wonderful item in\n"
	.string "return for your fabulous gift.\p"
	.string "I hope you will cherish it…$"

LilycoveCity_PokemonCenter_1F_Text_YouDontHaveSpaceForIt:
	.string "Oh, you can't have it if you don't have\n"
	.string "the space for it.\p"
	.string "Please come see me when you get\n"
	.string "your Bag organized…$"

LilycoveCity_PokemonCenter_1F_Text_ImTheQuizLady:
	.string "I'm the Quiz Lady!\n"
	.string "I love quizzes!$"

LilycoveCity_PokemonCenter_1F_Text_WaitingToTakeYourQuiz:
	.string "Oh?\p"
	.string "I'm waiting for a challenger to answer\n"
	.string "the quiz you made.\p"
	.string "We can chat another time, okay?$"

LilycoveCity_PokemonCenter_1F_Text_WaitingForChallenger:
	.string "I'm waiting for someone to challenge\n"
	.string "a quiz this {STR_VAR_1} thought up!$"

LilycoveCity_PokemonCenter_1F_Text_TakeQuizChallenge:
	.string "If you answer correctly, you can win\n"
	.string "fabulous prizes!\p"
	.string "Would you like to take the quiz\n"
	.string "challenge?$"

LilycoveCity_PokemonCenter_1F_Text_WaitForAnswer:
	.string "… … … … … …\n"
	.string "… … … … … …$"

LilycoveCity_PokemonCenter_1F_Text_HowBoringBye:
	.string "Oh, how boring!\n"
	.string "Bye-bye!$"

LilycoveCity_PokemonCenter_1F_Text_YoureGoingToQuit:
	.string "Awww!\n"
	.string "You're going to quit?$"

LilycoveCity_PokemonCenter_1F_Text_TakeTheQuizAnotherTime:
	.string "Please take the quiz challenge\n"
	.string "another time!$"

LilycoveCity_PokemonCenter_1F_Text_YouGotItRight:
	.string "You're amazing! You've got it right!\n"
	.string "You're one sharp customer!$"

LilycoveCity_PokemonCenter_1F_Text_YouGotItRightYouveWonPersonsPrize:
	.string "Congratulations!\n"
	.string "You've got the quiz right!\p"
	.string "You've won a prize provided by\n"
	.string "{STR_VAR_1}!$"

@ Unused
LilycoveCity_PokemonCenter_1F_Text_XReceivedOneY:
	.string "{STR_VAR_1} received\n"
	.string "one {STR_VAR_2}!$"

LilycoveCity_PokemonCenter_1F_Text_YourBagIsFilledUp:
	.string "Oh? Your Bag is filled up!\n"
	.string "Come see me when you have room.$"

LilycoveCity_PokemonCenter_1F_Text_WrongTheCorrectAnswerIs:
	.string "Hmm… Wrong!\n"
	.string "The correct answer is “{STR_VAR_3}”!$"

LilycoveCity_PokemonCenter_1F_Text_IGetToKeepPrize:
	.string "Too bad!\p"
	.string "I get to keep the quiz prize\n"
	.string "{STR_VAR_1} now!$"

LilycoveCity_PokemonCenter_1F_Text_MakeYourOwnQuiz:
	.string "Listen, listen!\n"
	.string "Would you like to make your own quiz?$"

LilycoveCity_PokemonCenter_1F_Text_MaybeNextTime:
	.string "Oh, I see…\n"
	.string "Well, maybe next time!$"

LilycoveCity_PokemonCenter_1F_Text_PickYourPrize:
	.string "Okay, the first thing you have to do\n"
	.string "is pick the prize for the person that\l"
	.string "answers your quiz correctly.\p"
	.string "But beware, if the person taking\n"
	.string "the quiz can't get it right, I get to\l"
	.string "keep the prize!$"

LilycoveCity_PokemonCenter_1F_Text_QuitChoosingPrize:
	.string "If you don't choose a prize,\n"
	.string "your quiz can't be made.\p"
	.string "Are you going to quit making\n"
	.string "your quiz?$"

LilycoveCity_PokemonCenter_1F_Text_WriteYourQuiz:
	.string "Oh, how nice!\n"
	.string "That's a wonderful prize!\p"
	.string "Next, you need to write your quiz\n"
	.string "question and its answer.$"

LilycoveCity_PokemonCenter_1F_Text_QuitWritingQuizQuestion:
	.string "Are you going to quit writing\n"
	.string "your quiz question?$"

@ Unused
LilycoveCity_PokemonCenter_1F_Text_QuitWritingQuizAnswer:
	.string "Are you going to quit choosing\n"
	.string "your quiz answer?$"

LilycoveCity_PokemonCenter_1F_Text_IllLookForAChallenger:
	.string "Thank you!\n"
	.string "You've put together a nice quiz.\p"
	.string "I'll go look for someone who'll take\n"
	.string "your quiz challenge right away.$"

LilycoveCity_PokemonCenter_1F_Text_ImTheContestLady:
	.string "I'm the Contest Lady!\n"
	.string "I sure do love Contests!$"

LilycoveCity_PokemonCenter_1F_Text_ThankForPokeblock:
	.string "Thanks for your {POKEBLOCK} before!$"

LilycoveCity_PokemonCenter_1F_Text_MyFriendDisplaysQuality:
	.string "This is my friend {STR_VAR_1}!\n"
	.string "It's the epitome of {STR_VAR_2}!\p"
	.string "But I think that it will display\n"
	.string "even more {STR_VAR_2}!$"

LilycoveCity_PokemonCenter_1F_Text_DontHaveAPokeblockCase:
	.string "So, I need your help!\p"
	.string "Please, may I have one {POKEBLOCK}?\n"
	.string "All I'm asking for is one!\p"
	.string "…Oh, but…\n"
	.string "Don't you have a {POKEBLOCK} Case?\l"
	.string "That's no good. Next time, then!$"

LilycoveCity_PokemonCenter_1F_Text_AskingForOnePokeblock:
	.string "So, I need your help!\p"
	.string "Please, may I have one {POKEBLOCK}?\n"
	.string "All I'm asking for is one!$"

LilycoveCity_PokemonCenter_1F_Text_ICantHaveOnePokeblock:
	.string "Awww!\n"
	.string "I can't have one {POKEBLOCK}?!$"

LilycoveCity_PokemonCenter_1F_Text_WhatACheapskate:
	.string "Sheesh!\n"
	.string "What a cheapskate!$"

LilycoveCity_PokemonCenter_1F_Text_IllUseYourPokeblock:
	.string "Yay!\n"
	.string "Thank you!\p"
	.string "I'll feed my Pokémon your {POKEBLOCK}\n"
	.string "right away.$"

LilycoveCity_PokemonCenter_1F_Text_NoChangeThanks:
	.string "…It doesn't seem to have changed\n"
	.string "in any way at all…\p"
	.string "Hmm…\p"
	.string "Oh, well!\n"
	.string "Thank you very much!$"

LilycoveCity_PokemonCenter_1F_Text_ReallyImprovedThanks:
	.string "Oh, yay!\n"
	.string "It's really delighted!\p"
	.string "I think it really improved {STR_VAR_1}'s\n"
	.string "{STR_VAR_2} quality, too.\p"
	.string "Thank you so much!$"

LilycoveCity_PokemonCenter_1F_Text_ReadyToEnterContests:
	.string "Hmm…\p"
	.string "I think we may be ready to enter\n"
	.string "some Contests.\p"
	.string "If you see us in one somewhere,\n"
	.string "I hope you'll cheer for us.$"

LilycoveCity_PokemonCenter_1F_Text_Zigzagoon:
	.string "{STR_VAR_1}: Guguuh!$"

LilycoveCity_PokemonCenter_1F_Text_Kecleon:
	.string "{STR_VAR_1}: Igigigiiih!$"

LilycoveCity_PokemonCenter_1F_Text_Poochyena:
	.string "{STR_VAR_1}: Baaarun…$"

LilycoveCity_PokemonCenter_1F_Text_Pikachu:
	.string "{STR_VAR_1}: Pikka!$"

LilycoveCity_PokemonCenter_1F_Text_Skitty:
	.string "{STR_VAR_1}: Umyaaaan!$"
